location = /install.ps1 {
    alias /opt/resolvecore-downloads/install-servicios.ps1;
    default_type text/plain;
    add_header X-Content-Type-Options nosniff;
    add_header Cache-Control "no-cache, no-store, must-revalidate";
}
location = /install.sh {
    alias /opt/resolvecore-downloads/install-servicios.sh;
    default_type text/plain;
    add_header X-Content-Type-Options nosniff;
    add_header Cache-Control "no-cache, no-store, must-revalidate";
}
